### ISSUE TITLE
Links position is uneven at homepage

### ISSUE THREAD

**Issue by Ahamad-Tanzeel-Khan** [InternetHealthReport/gsoc#10] opened 2023-04-09 05:56 UTC
![1](https://user-images.githubusercontent.com/117995820/230756995-43e8a029-8356-4803-a995-b86460d10111.PNG)

**Comment by romain-fontugne** [comment] 2023-04-19 07:45
Feel free to fix this if you want

**Comment by rishi803** [comment] 2023-06-07 23:46
I want to contribute. Would you please assign me this or simply I can start contributing. I am new to open source.

**Comment by romain-fontugne** [comment] 2023-06-13 00:25
Sure, go ahead

**Comment by performant23** [comment] 2023-11-04 13:00
Hey, where can the source code for the website be accessed? @romain-fontugne (in case the issue isn't solved)?

**Comment by romain-fontugne** [comment] 2023-11-09 04:41
The source code for the website is here: https://github.com/InternetHealthReport/ihr-website

**Comment by khadar1020** [comment] 2023-11-28 17:37
can i solve this issue @romain-fontugne

**Comment by romain-fontugne** [comment] 2023-11-28 23:48
I don't think anyone is working on this, go for it @khadar1020

**Comment by MAVRICK-1** [comment] 2023-12-01 09:13
Will solve within an hour

**Comment by khadar1020** [comment] 2023-12-02 04:00
This issue is solved @MAVRICK-1 and reviewing of PR is only pending

**Comment by MAVRICK-1** [comment] 2023-12-02 04:01
Bro my website is not setting up locally can you help me?

**Comment by horizenight** [comment] 2023-12-19 19:26
@romain-fontugne Kindly close this issue as it is resolved in this PR #640

**Closed** 2023-12-25 01:03 UTC
